# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "AuthenticationViewController"
pod 'HockeySDK', '~> 5.1.2'

  # Pods for SampleApp
end
